---
title: "Linear Regression 2019-2020 HistoricData"
output: html_document
---

```{r setup, include=FALSE}
library(plotly)
library('sqldf')
library(Metrics)
library(caTools)
library(MASS)
library(dplyr)
```

```{r read_data}
filename = '2016-2020-Historic-Data.csv'
data<- read.csv(filename , sep=',', header=TRUE,fill = TRUE, stringsAsFactors = FALSE)

```

```{r linear regression model TOTAL MONTHLY ENERGY}
  
  data = data[(25561:39482),]  ## getting 2019  and 2020 data
  data = subset(data, !is.na(hourly_load)) ## 2019 DEC, last some days having NA for hourly_load, removing them
  # data = data[,c(-4,-5,-15,-16,-26,-27,-37,-38,-48,-49,-59,-60,-70,-71,-81,-82,-92,-93)] ## removing categorical cols
  data = data[,c(1,2,9)]
  data$month <- strftime(data$Time, '%m')
  data$year <- strftime(data$Time, '%Y')
  data_without_time= data[,c(-1)]
  data_without_time[is.na(data_without_time)] = 0
  total_energy_df <- aggregate(hourly_load ~month+year, data_without_time, sum)
  weather_df <- aggregate(Lahore_apparentTemperature ~month+year, data_without_time, mean)
  total_energy_df = merge(total_energy_df, weather_df)
  # total_energy_df <- total_energy_df[,-c(1,2)] ## remove month and year col
  total_energy_df
  # train = head(total_energy_df, 16)
  # valid = tail(total_energy_df, 3)
  

forward_model = lm(hourly_load~1,data=train)
backward_model = lm(hourly_load~., data=train)
step.model <-step(forward_model, direction = "forward", scope = formula(backward_model))
summary(step.model)

full.model <- lm(hourly_load ~., data = train)
# Stepwise regression model
full.model <- stepAIC(full.model, direction = "both", trace=FALSE)

summary(full.model)

# 
# selected_cols = c('hourly_load', 'Predicted','Lahore_precipIntensity', 
#     'Lahore_temperature','Lahore_apparentTemperature','Lahore_dewPoint', 
#     'Lahore_humidity','Lahore_pressure','Lahore_windGust','Multan_precipIntensity', 
#     'Multan_apparentTemperature','Multan_humidity','Multan_pressure', 
#     'Multan_windSpeed','Multan_windGust','Faislabad_precipIntensity', 
#     'Faislabad_precipProbability', 'Faislabad_dewPoint','Faislabad_humidity', 
#     'Faislabad_pressure','Faislabad_windSpeed','Faislabad_windGust', 
#     'Quetta_temperature','Quetta_apparentTemperature','Quetta_humidity', 
#     'Quetta_pressure','Quetta_windSpeed','Peshawar_precipProbability', 
#     'Peshawar_temperature','Peshawar_apparentTemperature','Peshawar_humidity', 
#     'Peshawar_pressure','Peshawar_windSpeed','Gujranwala_precipIntensity', 
#     'Gujranwala_precipProbability','Gujranwala_temperature','Gujranwala_apparentTemperature', 
#     'Gujranwala_humidity','Gujranwala_windSpeed','Gujranwala_windGust', 
#     'Hyderabad_precipIntensity','Hyderabad_precipProbability' ,
#     'Hyderabad_temperature','Hyderabad_apparentTemperature','Hyderabad_dewPoint' ,
#     'Hyderabad_pressure','Hyderabad_windSpeed','Hyderabad_windGust', 
#     'Sukkur_precipIntensity','Sukkur_precipProbability','Sukkur_temperature', 
#     'Sukkur_apparentTemperature','Sukkur_dewPoint','Sukkur_humidity', 
#     'Sukkur_pressure','Islamabad_precipProbability','Islamabad_temperature', 
#     'Islamabad_apparentTemperature','Islamabad_dewPoint','Islamabad_humidity', 
#     'Islamabad_pressure','Islamabad_windSpeed', 'Islamabad_windGust')
# Model = lm(hourly_load~Predicted+Lahore_precipIntensity+Lahore_temperature+Lahore_apparentTemperature+Lahore_dewPoint+Lahore_humidity+Lahore_pressure+Lahore_windGust+
#     Multan_precipIntensity+Multan_apparentTemperature+Multan_humidity+Multan_pressure+Multan_windSpeed+Multan_windGust+Faislabad_precipIntensity+Faislabad_precipProbability+Faislabad_dewPoint+Faislabad_humidity+Faislabad_pressure+Faislabad_windSpeed+Faislabad_windGust+Quetta_temperature+Quetta_apparentTemperature+Quetta_humidity+Quetta_pressure+Quetta_windSpeed+Peshawar_precipProbability+Peshawar_temperature+Peshawar_apparentTemperature+Peshawar_humidity+Peshawar_pressure+Peshawar_windSpeed+Gujranwala_precipIntensity+Gujranwala_precipProbability+Gujranwala_temperature+Gujranwala_apparentTemperature+Gujranwala_humidity+Gujranwala_windSpeed+Gujranwala_windGust+Hyderabad_precipIntensity+Hyderabad_precipProbability+Hyderabad_temperature+Hyderabad_apparentTemperature+Hyderabad_dewPoint+Hyderabad_pressure+Hyderabad_windSpeed+Hyderabad_windGust+Sukkur_precipIntensity+Sukkur_precipProbability+Sukkur_temperature+Sukkur_apparentTemperature+Sukkur_dewPoint+Sukkur_humidity+Sukkur_pressure+Islamabad_precipProbability+Islamabad_temperature+Islamabad_apparentTemperature+Islamabad_dewPoint+Islamabad_humidity+ Islamabad_pressure+Islamabad_windSpeed+Islamabad_windGust, data= data_without_time[,-c(84,85)])

  ModelSummary = summary(Model)
  print(ModelSummary)
  pred <- predict(Model, select(valid,selected_cols))
  actual <- valid$hourly_load
  printStats(ModelSummary, actual, pred)
  
  
  ## FORECASTING 2021 
  filename1 = 'NPCC Historic Data 2021-01-01-2021-07-31.csv'
  next_year_data = read.csv(filename1 , sep=',', header=TRUE,fill = TRUE, stringsAsFactors = FALSE)
  next_year_data = subset(next_year_data, !is.na(hourly_load))
  next_year_data = next_year_data[,c(-4,-5,-15,-16,-26,-27,-37,-38,-48,-49,-59,-60,-70,-71,-81,-82,-92,-93)] ## removing categorical cols
  next_year_data$month <- strftime(next_year_data$Time, '%m')
  next_year_data= next_year_data[,c(-1)]  ## remove time col
  next_year_data[is.na(next_year_data)] = 0
  
  test_new_year_data <- aggregate(. ~month, next_year_data, sum)
  pred_new_year <- predict(Model, select(test_new_year_data,selected_cols))
  actual_new_year <- test_new_year_data$hourly_load
  printStats(ModelSummary, actual_new_year, pred_new_year)
  x_axis = c('June 2019','July 2019','Aug 2019','Sep 2019','Oct 2019','Nov 2019','Dec 2019','Jan 2020','Feb 2020','March 2020','April 2020','May 2020','June 2020','July 2020','Aug 2020','Sep 2020','Oct 2020','Nov 2020', 'Dec 2020')
  x_axis_new = c('Jan 2021', 'Feb 2021', 'March 2021', 'April 2021', 'May 2021', 'June 2021', 'July 2021')
  fig<-plot_ly(total_energy_df, x=x_axis, y= total_energy_df$hourly_load, mode='lines', type='scatter', name="Total Monthly Energy")
  fig<- fig%>% add_lines( x=c(20,21,22,23,24,25,26), pred_new_year, name="Total Monthly Energy Forecast 2021")
  fig<- fig%>% add_lines( x=c(20,21,22,23,24,25,26), actual_new_year, name="Total Monthly Energy 2021 ")
  fig

```


```{r pressure, echo=FALSE}
 

  # data[is.na(data)]=0
  # timeSlices <- createTimeSlices(1:nrow(data), initialWindow = 36, horizon = 12, fixedWindow = TRUE)
  # # print(timeSlices)
  # trainSlices <- timeSlices[[1]]
  # testSlices <- timeSlices[[2]]
  # for(i in 1:length(trainSlices)){
  #   # plsFitTime <- train(hourly_load ~.,
  #   #                     data = data[trainSlices[[i]],],
  #   #                     method = "pls",
  #   #                     preProc = c("center", "scale"))
  #   # pred <- predict(plsFitTime,data[testSlices[[i]],])
  #   Model = lm(hourly_load~., data=data[trainSlices[[i]],])
  #   print(summary(Model))
  #   pred <- predict(Model, data[testSlices[[i]],])
  # 
  #   true <- data$hourly_load[testSlices[[i]]]
  #   # plot(true, col = "red", ylab = "true (red) , pred (blue)",
  #   #      main = i, ylim = range(c(pred,true)))
  #   # points(pred, col = "blue")
  #   print(mape(true, pred))
  # }
```
``` {r aggregate,}

 aggregate_func <- function(data,method){
   if(method == 'total_monthly_energy_forecast'){
       total_energy_df <- aggregate(. ~month+year, data_without_time, sum)
   }
   else{
     
   }
 }

```


```{r stats}
mape <- function(actual,pred){
    mape <- mean(abs((actual - pred)/actual))*100
    return (mape)
}

RSQUARE = function(y_actual,y_predict){
  cor(y_actual,y_predict)^2
}
  
printStats <- function(ModelSummary, actual, pred){
  # SSE <- sum((actual - pred) ^2)
  # SST <- sum((actual - mean(actual)) ^2)
  # print(paste("R squared for test data" ,1-(SSE/SST)) )  ## value of R^2 on test dataset
  print(paste("R^2 : ", RSQUARE(actual,pred)))
  print(paste("RMS for test data: " , mean(ModelSummary$residuals^2)))
 print(paste("MAE Mean Absolute Error: " ,mae(actual, pred)))
 print(paste("MASE (Mean Absolute Scaled Error): " ,mase(actual, pred)))
  print(paste("mape (Mean Absolute Percent Error) : " ,mape(actual, pred)))
  print(paste("RMSE (Root Mean Squared Error): " ,rmse(actual, pred)))
  print(paste("RAE (Relative Absolute Error): " ,rae(actual, pred)))
}

```







